### ISSUE TITLE
error: default argument given for parameter

### ISSUE THREAD

**Issue by sergiocntr** [djGrrr/Int64String#1]
Hi ,I had to remove the default parameters in the .cpp file as they are already defined in .h file,otherwise  doesn't compile.

**Comment by djGrrr** [comment]
Thanks for reporting this. I'm fairly new to C++ and I did not know this was a problem. It compiled fine on my Arduino IDE
This is fixed in 1ddd0680144caeaa98e32fc8654e849f53ebc449

**Comment by sergiocntr** [comment]
Hi,you are welcome. As for me,that was my first issue. 😅. Thank you for
sharing your code,I wish you all the best.

Il giorno sab 3 nov 2018, 01:42 djGrrr <notifications@github.com> ha
scritto:
