### ISSUE TITLE
Byte order is reversed

### ISSUE THREAD

**Issue by iMina** [djGrrr/Int64String#4]
Hello,
I was trying to get a String of the 6-byte MAC address of my ESP32 and I found that the byte order is reversed.
The vendor part of ESP MAC addresses is `80:7D:3A` which should be in the beginning of the string, but the ouput is `38CDD33A7D80`, which puts the byte values correclty but in reverse order.

**Comment by djGrrr** [comment]
Hi, I think this board probably uses a big endian processor vs little endian, so the byte order is reversed. What is the output if you pass the integer through __builtin_bswap64() before int64String?
ie:
`int64String(__builtin_bswap64(mac_address), 16);`

**Comment by iMina** [comment]
`__builtin_bswap64(mac_address)` in deed works !
However, since the MAC is only 6 bytes, `__builtin_bswap64(mac_address)` adds two bytes of zeros to the end of the MAC, ie, `807D3AD3CD880000`.
This is ok for the hexadecimal MAC, however I also need the decimal representation, which will mess up the number badly.

**Comment by djGrrr** [comment]
Try this as a workaround:
`int64String(__builtin_bswap64(mac_address) >> 16 & 0xFFFFFFFFFFFFULL, 10)`
this should shift the number over by 16 bits, and only allow the 48bits of the mac address in the case where the shift would "wrap" arround, i do not have access to a big endian board so it will be difficult to create a proper fix for this

**Comment by iMina** [comment]
Okay, this workaround works well.
Closing ...
